# Site title and subtitle. This is used in _includes/header.html
title: 'MailWatch for MailScanner'
subtitle: ''

# Enable/show navigation. There are these options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/mailwatch/MailWatch'

# Default categories (in order) to appear in the navigation
sections: [
    ['install', 'Installation'],
    ['optional', 'Optional Setup'],
    ['using', 'Using MailWatch'],
    ['dev', 'Developers'],
    ['post', 'Posts']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Since these are pages, it doesn't really matter
future: true

#enable some pugins
gems:
  - jekyll-sitemap

# Exclude non-site files
exclude: ['bin', 'README.md', 'LICENSE.md']

# Use the kramdown Markdown renderer
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
